//TODO:- this was designed to be a namespace but.. babel issues
export enum Meta {
  NEW_COMPONENT = "NEW_COMPONENT",
  SET_COMPONENT = "SET_COMPONENT",
  SET_PAGE = "SET_PAGE",
  SUBMIT = "SUBMIT",
  DELETE = "DELETE",
  VALIDATE = "VALIDATE",
  ADD_STATIC_LIST = "ADD_STATIC_LIST",
}

export enum Schema {
  EDIT_SCHEMA_MIN = "EDIT_SCHEMA_MIN",
  EDIT_SCHEMA_MAX = "EDIT_SCHEMA_MAX",
  EDIT_SCHEMA_PRECISION = "EDIT_SCHEMA_PRECISION",
  EDIT_SCHEMA_LENGTH = "EDIT_SCHEMA_LENGTH",
  EDIT_SCHEMA_REGEX = "EDIT_SCHEMA_REGEX",
}

export enum Fields {
  EDIT_TITLE = "EDIT_TITLE",
  EDIT_NAME = "EDIT_NAME",
  EDIT_CONDITION = "EDIT_CONDITION",
  EDIT_HELP = "EDIT_HELP",
  EDIT_CONTENT = "EDIT_CONTENT",
  EDIT_TYPE = "EDIT_TYPE",
}

export enum Options {
  EDIT_OPTIONS_HIDE_TITLE = "EDIT_OPTIONS_HIDE_TITLE",
  EDIT_OPTIONS_REQUIRED = "EDIT_OPTIONS_REQUIRED",
  EDIT_OPTIONS_HIDE_OPTIONAL = "EDIT_OPTIONS_HIDE_OPTIONAL",
  EDIT_OPTIONS_FILE_UPLOAD_MULTIPLE = "EDIT_OPTIONS_FILE_UPLOAD_MULTIPLE",
  EDIT_OPTIONS_CLASSES = "EDIT_OPTIONS_CLASSES",
  EDIT_OPTIONS_MAX_DAYS_IN_FUTURE = "EDIT_OPTIONS_MAX_DAYS_IN_FUTURE",
  EDIT_OPTIONS_MAX_DAYS_IN_PAST = "EDIT_OPTIONS_MAX_DAYS_IN_PAST",
  EDIT_OPTIONS_CONDITION = "EDIT_OPTIONS_CONDITION",
  EDIT_OPTIONS_TYPE = "EDIT_OPTIONS_TYPE",
  EDIT_OPTIONS_ROWS = "EDIT_OPTIONS_ROWS",
}

export enum ComponentList {
  EDIT_LIST_ITEM_CONDITION = "EDIT_LIST_ITEM_CONDITION",
  SUBMIT_LIST_ITEM = "SUBMIT_LIST_ITEM",
  ADD_LIST_ITEM = "ADD_LIST_ITEM",
  EDIT_LIST_ITEM = "EDIT_LIST_ITEM",
  EDIT_LIST = "EDIT_LIST",
  SET_SELECTED_LIST = "SET_SELECTED_LIST",
  LIST_ITEM_VALIDATION_ERRORS = "LIST_ITEM_VALIDATION_ERRORS",
}

export const Actions = {
  ...Meta,
  ...Schema,
  ...Fields,
  ...Options,
  ...ComponentList,
};
export type ComponentActions = typeof Actions;
